version: '2'
services:
  db:
    image: postgres
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/buscorepublica
    ports:
      - "3000:3000"
    depends_on:
      - db
      - selenium
    environment:
      - SELENIUM_REMOTE_HOST=selenium
  selenium:
    image: selenium/standalone-firefox
    container_name: selenium
    ports:
      - "4444:4444"